from langchain_huggingface import ChatHuggingFace, HuggingFaceEndpoint
from dotenv import load_dotenv
from langchain_core.prompts import PromptTemplate
from langchain_core.output_parsers import JsonOutputParser

load_dotenv()

llm = HuggingFaceEndpoint(
    repo_id="HuggingFaceH4/zephyr-7b-beta",
    task="text-generation"
)

model = ChatHuggingFace(llm=llm)

parser = JsonOutputParser()

template = PromptTemplate(
    template="Give me 5 Facts about {topic} \n{format_instructions}",
    input_variables = ["topic"],
    partial_variables={"format_instructions": parser.get_format_instructions()}
)

# prompt = template.format()
# print(prompt)
# result = model.invoke(prompt)
# output = parser.parse(result.content) #parses the string output into a dictionary using the format instructions provided in the prompt
# print(output)
# print(type(output)) #returns a dictionary
# print(output['name']) #same access as a normal dictionary
# (the whole above code can be written in a more concise way using the chain operator as shown below)

chain = template | model | parser
result = chain.invoke({'topic': 'black hole theory'})
print(result)
print(type(result))
# jsonoutputparser does not return a schema like the pydantic output parser, it just returns a dictionary with the keys specified in the format instructions and the values generated by the model.